services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000" # Expose Chroma on localhost
    expose:
      - "8000" # Expose container port internally
    volumes:
      - ./chroma_data:/chroma/chroma # ✅ Correct volume path
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_PERSISTENT=true
      - CHROMA_DB_PATH=/chroma/chroma # ✅ Matches volume pathls .
    restart: always
